services:
  mlflow:
    build: .
    container_name: mlflow
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:/app/data/mlruns
    ports:
      - "5000:5000"
    volumes:
      - ./data/mlruns:/app/data/mlruns
      - ./data/models:/app/data/models
    environment:
      - PYTHONPATH=/app

  api:
    build: .
    container_name: api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mlflow
    environment:
      - BASE_DIR=/app
      - PYTHONPATH=/app

  watcher:
    build: .
    container_name: watcher
    command: python3 -m api.watcher
    volumes:
      - .:/app
    depends_on:
      - mlflow
    environment:
      - BASE_DIR=/app
      - PYTHONPATH=/app

  airflow:
    build: .
    container_name: airflow
    environment:
      - AIRFLOW_HOME=/app/airflow
      - PYTHONPATH=/app
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Baitur --lastname Tashbaev --role Admin --email tawbaev777@gmail.com --password admin && airflow api-server --port 8080 & airflow scheduler & airflow dag-processor & airflow triggerer"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mlflow
